version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    main: .
    binary: somafm-player
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1

  - id: darwin-arm64
    main: .
    binary: somafm-player
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  footer: >-
    See [CHANGELOG.md](https://github.com/jonasbn/somafm-player/blob/main/CHANGELOG.md) for the full curated changelog.
